### ISSUE TITLE
Reactor Inspector doesn't work in prefab view

### ISSUE THREAD

**Issue by ddugganCRA** [charles-river-analytics/VSDK-Unity#27]
**Describe the bug**
The inspector for Reactors show an error message instead of rendering in the prefab view. This seems to just be a UI issue as any data created in the scene view and saved to a prefab loads probably.

**To Reproduce**
1. Create a cube, attach the Interactable Object script, a reactor, and a color change reaction
2. Turn the object into a prefab
3. Open in prefab editor

**Expected behavior**
You should still be able to set up a Reactor in the prefab window (and in fact, it's probably best practice to do so)

**Comment by ddugganCRA** [comment]
@VR-Nic can you take a look at this when you have a chance? You know that code better than I do.

**Comment by VR-Nic** [comment]
What's the exact error message you are getting and what version of Unity are you using? I just tried this in 2019.2.3f1 and was able to set up reactor as expect in the Prefab Editor.

**Comment by ddugganCRA** [comment]
"No Reactions are currently in the scene" in version 2019.2.3

![reactor error](https://user-images.githubusercontent.com/45572975/73020831-6b50e680-3df4-11ea-95ef-8a96023532e3.PNG)

**Comment by VR-Nic** [comment]
Interesting. I'll take a further dive into this when I get the chance.

**Comment by VR-Nic** [comment]
Just did a quick test in a blank scene. Seems like FindObjectsOfType<>() will use the underlying scene to find the object, not the Prefab editor. However, if you have the prefab with a reaction in the scene you are working in and save, then the error message will go away. I'll check to see if there is a way to see if you are in the Prefab Editor when I have some more time to avoid this issue, but it is definitely minor.

**Comment by VR-Nic** [comment]
@ddugganCRA I see 3 options to handle this.

1)	Do nothing since this is a small edge case. The user can save the prefab before working on it and as long as it is in the scene, the error message will go away.
2)	Remove the error message since it is only meant to say there are no reactions in the scene, the end user can figure this out easily when trying to assign reactions.
3)	Use PrefabStageUtility.GetCurrentPrefabStage() to determine if in Prefab Editor mode. This call is in Unity’s experimental API though, so it will change sometime in the future. This also is only available with the new Prefab system, so keep that in mind.

Let me know which you prefer and I'll get to it.
